import type { MissionControlState } from "@/lib/types";
import { PROJECT_OPS } from "@/lib/seed/project-ops";

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const seedState: MissionControlState = {
  interfaces: [
    { id: "cursor", name: "Cursor", description: "Main hub — fast edits, UI, file-by-file", icon: "⌘" },
    { id: "claude-code", name: "Claude Code", description: "Multi-file, terminal, autonomous coding", icon: "◈" },
    { id: "regular-claude", name: "Regular Claude", description: "Planning, specs, architecture, prompts", icon: "◉" },
    { id: "future-custom", name: "Future / Custom", description: "Placeholder for other tools", icon: "◇" },
  ],
  modelClasses: [
    { id: "cheap-fast", name: "Cheap Fast", description: "Quick passes, low cost", costTier: "low" },
    { id: "balanced", name: "Balanced", description: "Default quality/cost balance", costTier: "mid" },
    { id: "deep-reasoning", name: "Deep Reasoning", description: "Hard problems, tradeoffs", costTier: "high" },
    { id: "code-heavy", name: "Code Heavy", description: "Implementation focus", costTier: "mid" },
    { id: "review-heavy", name: "Review Heavy", description: "Audit and review focus", costTier: "mid" },
    { id: "planning-heavy", name: "Planning Heavy", description: "Specs and architecture", costTier: "mid" },
    { id: "long-context", name: "Long Context", description: "Large repo / epic scope", costTier: "high" },
    { id: "autonomous-heavy", name: "Autonomous Heavy", description: "Agent runs with less hand-holding", costTier: "high" },
  ],
  settings: {
    jeffMode: "caveman",
    cavemanDefault: true,
    costSaveMode: true,
    defaultInterface: "cursor",
    autoRoute: true,
    preferredModelClass: "balanced",
    preferredBotSequence: ["control-tower", "project-god-bot", "builder-bot", "reviewer-bot"],
    compactMode: false,
    mobileMode: false,
    voiceEnabled: true,
    voiceMode: "push-to-talk",
    voiceResponseEnabled: true,
    autoDiscoverProjects: true,
    discoverUnknownFolders: true,
    projectsRoots: ["C:\\Projects", "C:\\vercel generator"],
    lastDiscoveryAt: null,
    lastDiscoveryCount: 0,
    monthlyCostThresholdUsd: 100,
    costWarningPercent: 80,
    experienceLevel: "comfortable",
    uiMode: "easy",
    guidedJourneyStep: 0,
    guidedJourneyComplete: false,
    guidedJourneyDismissed: false,
    guidedJourneyLastBuildAt: null,
    productionUrl: null,
  },
  projects: [
    {
      id: "proj-demand-generator",
      name: "Demand Generator Pro",
      slug: "demand-generator-pro",
      type: "Legal SaaS",
      stack: ["Next.js 16", "Postgres", "Vercel", "PDF/AI"],
      status: "active",
      priority: "P1",
      path: "C:\\vercel generator",
      github: "https://github.com/jpro99/Demand-Generator-Pro",
      description: "Legal demand letter generator — matters, docs, AI extraction.",
      goals: ["Harden security", "Ship field capture mobile", "Reduce Vercel costs"],
      risks: ["Migration order quirks", "Duplicate local folders"],
      roadmap: ["Security pass", "Mobile polish", "Rename temp folder"],
      assignedGodBotId: "bot-god-demand",
      workerBotIds: [
        "bot-pdf",
        "bot-ai",
        "bot-security",
        "bot-deploy",
        "bot-neuro",
        "bot-exhibits",
        "bot-damages",
        "bot-conductor",
      ],
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      activeBotStrategy: "God Bot + PDF/AI workers",
      jeffMode: "caveman",
      lastUpdated: daysAgo(1),
      ops: PROJECT_OPS["proj-demand-generator"],
    },
    {
      id: "proj-kepi-bot",
      name: "Kepi Bot",
      slug: "kepi-bot",
      type: "Control / Chat",
      stack: ["Next.js", "xAI Grok", "Vercel"],
      status: "active",
      priority: "P1",
      path: "C:\\Projects\\Kepi Bot",
      github: "https://github.com/jpro99/Kepi-Bot",
      description: "Roster archive. Live Talk + routing lives in Jeff OS.",
      goals: ["Point people at Jeff OS Talk", "Keep roster in sync"],
      risks: ["Two chat UIs confuse Jeff"],
      roadmap: ["Talk here", "Archive there"],
      assignedGodBotId: "bot-control-tower",
      workerBotIds: ["bot-line-architect", "bot-memory"],
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      activeBotStrategy: "Control Tower stations, Jeff OS Talk answers",
      jeffMode: "caveman",
      lastUpdated: daysAgo(0),
      ops: PROJECT_OPS["proj-jeff-os"],
    },
  ],
  bots: [
    {
      id: "bot-control-tower",
      type: "control-tower",
      name: "Control Tower",
      role: "Portfolio orchestrator",
      description: "Routes Jeff to right project, priority, and handoff.",
      group: "control",
      preferredInterface: "cursor",
      preferredModelClass: "planning-heavy",
      promptPreview: "Read CONTROL_TOWER.md + PROJECT_INDEX.md. Route Jeff.",
      projectIds: [],
    },
  ],
  tasks: [],
  routingPresets: [],
  routingHistory: [],
  workspace: {
    activeProjectId: "proj-demand-generator",
    activeTaskId: null,
    recentProjectIds: ["proj-demand-generator"],
    queueTaskIds: [],
    activeRoute: null,
    routeMode: "auto",
    pinnedProjectIds: ["proj-demand-generator", "proj-tripflow"],
    openWorkspaceIds: ["proj-demand-generator"],
    minimizedProjectIds: [],
    handoffNote: "",
    voice: { lastVoiceCommand: null, micPermissionState: "unknown" },
  },
  activity: [],
};

export const STORAGE_KEY = "jeff-mission-control-v9";
