import type { MissionControlState } from "@/lib/types";
import { PROJECT_OPS } from "@/lib/seed/project-ops";

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const seedState: MissionControlState = {
  interfaces: [
    { id: "cursor", name: "Cursor", description: "Main hub — fast edits, UI, file-by-file", icon: "⌘" },
    { id: "claude-code", name: "Claude Code", description: "Multi-file, terminal, autonomous coding", icon: "◈" },
    { id: "regular-claude", name: "Regular Claude", description: "Planning, specs, architecture, prompts", icon: "◉" },
    { id: "future-custom", name: "Future / Custom", description: "Placeholder for other tools", icon: "◇" },
  ],
  modelClasses: [
    { id: "cheap-fast", name: "Cheap Fast", description: "Quick passes, low cost", costTier: "low" },
    { id: "balanced", name: "Balanced", description: "Default quality/cost balance", costTier: "mid" },
    { id: "deep-reasoning", name: "Deep Reasoning", description: "Hard problems, tradeoffs", costTier: "high" },
    { id: "code-heavy", name: "Code Heavy", description: "Implementation focus", costTier: "mid" },
    { id: "review-heavy", name: "Review Heavy", description: "Audit and review focus", costTier: "mid" },
    { id: "planning-heavy", name: "Planning Heavy", description: "Specs and architecture", costTier: "mid" },
    { id: "long-context", name: "Long Context", description: "Large repo / epic scope", costTier: "high" },
    { id: "autonomous-heavy", name: "Autonomous Heavy", description: "Agent runs with less hand-holding", costTier: "high" },
  ],
  settings: {
    jeffMode: "caveman",
    cavemanDefault: true,
    costSaveMode: true,
    defaultInterface: "cursor",
    autoRoute: true,
    preferredModelClass: "balanced",
    preferredBotSequence: ["control-tower", "project-god-bot", "builder-bot", "reviewer-bot"],
    compactMode: false,
    mobileMode: false,
    voiceEnabled: true,
    voiceMode: "push-to-talk",
    voiceResponseEnabled: true,
    autoDiscoverProjects: true,
    discoverUnknownFolders: true,
    projectsRoots: ["C:\\Projects", "C:\\vercel generator"],
    lastDiscoveryAt: null,
    lastDiscoveryCount: 0,
    monthlyCostThresholdUsd: 100,
    costWarningPercent: 80,
    experienceLevel: "comfortable",
    uiMode: "classic",
    guidedJourneyStep: 0,
    guidedJourneyComplete: false,
    guidedJourneyDismissed: false,
    guidedJourneyLastBuildAt: null,
  },
  projects: [
    {
      id: "proj-demand-generator",
      name: "Demand Generator Pro",
      slug: "demand-generator-pro",
      type: "Legal SaaS",
      stack: ["Next.js 16", "Postgres", "Vercel", "PDF/AI"],
      status: "active",
      priority: "P1",
      path: "C:\\vercel generator",
      github: "https://github.com/jpro99/Demand-Generator-Pro",
      description: "Legal demand letter generator — matters, docs, AI extraction.",
      goals: ["Harden security", "Ship field capture mobile", "Reduce Vercel costs"],
      risks: ["Migration order quirks", "Duplicate local folders"],
      roadmap: ["Security pass", "Mobile polish", "Rename temp folder"],
      assignedGodBotId: "bot-god-demand",
      workerBotIds: ["bot-pdf", "bot-ai", "bot-security", "bot-deploy"],
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      activeBotStrategy: "God Bot + PDF/AI workers",
      jeffMode: "caveman",
      lastUpdated: daysAgo(1),
      ops: PROJECT_OPS["proj-demand-generator"],
    },
    {
      id: "proj-home-compass",
      name: "Home Compass",
      slug: "home-compass",
      type: "Consumer / Family",
      stack: ["Next.js 15", "Supabase", "Tailwind"],
      status: "active",
      priority: "P2",
      path: "C:\\Projects\\household-compass",
      description: "Household continuity — emergency, vault, money, family.",
      goals: ["Mobile emergency UX", "Supabase sync hardening"],
      risks: ["PII sensitivity", "Boilerplate README"],
      roadmap: ["Family cloud", "Emergency quick flow", "PIN security"],
      assignedGodBotId: "bot-god-compass",
      workerBotIds: ["bot-ux", "bot-security"],
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      activeBotStrategy: "God Bot + Feature worker",
      jeffMode: "caveman",
      lastUpdated: daysAgo(3),
      ops: PROJECT_OPS["proj-home-compass"],
    },
    {
      id: "proj-tripflow",
      name: "TripFlow / RoamWise",
      slug: "kepi-travel",
      type: "Travel Platform",
      stack: ["Next.js", "MapLibre", "Clerk", "Capacitor"],
      status: "active",
      priority: "P1",
      path: "C:\\Projects\\Kepi Travel\\kepi-travel",
      description: "Travel assistant — trips, maps, ops, mobile.",
      goals: ["Build before push discipline", "Consolidate forks"],
      risks: ["Failed Vercel builds cost money", "3 repo folders"],
      roadmap: ["Ops control", "Offline outbox", "Mobile notifications"],
      assignedGodBotId: "bot-god-travel",
      workerBotIds: ["bot-builder", "bot-test", "bot-deploy"],
      preferredInterface: "claude-code",
      preferredModelClass: "autonomous-heavy",
      activeBotStrategy: "God Bot + build gate",
      jeffMode: "caveman",
      lastUpdated: daysAgo(2),
      ops: PROJECT_OPS["proj-tripflow"],
    },
    {
      id: "proj-keps-trading",
      name: "Keps Trading",
      slug: "keps-trading",
      type: "Trading / Finance",
      stack: ["TBD", "APIs", "Data"],
      status: "idea",
      priority: "P2",
      description: "Trading tooling and automation — scope TBD.",
      goals: ["Define MVP", "Risk model", "Data feeds"],
      risks: ["Regulatory", "Cost of bad automation"],
      roadmap: ["Spec phase", "Paper trading", "Alerting"],
      assignedGodBotId: "bot-god-keps",
      workerBotIds: ["bot-architect", "bot-data-model"],
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      activeBotStrategy: "Spec + Architect first",
      jeffMode: "caveman",
      lastUpdated: daysAgo(14),
      ops: PROJECT_OPS["proj-keps-trading"],
    },
    {
      id: "proj-points-miles",
      name: "Points & Miles Education",
      slug: "points-miles-edu",
      type: "Education / Content",
      stack: ["Next.js", "Content", "Community"],
      status: "prototype",
      priority: "P3",
      description: "Education platform for points & miles strategies.",
      goals: ["Curriculum outline", "Landing MVP"],
      risks: ["Scope creep", "Content maintenance"],
      roadmap: ["Spec", "Content model", "Beta landing"],
      assignedGodBotId: "bot-god-points",
      workerBotIds: ["bot-spec", "bot-ux", "bot-docs"],
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      activeBotStrategy: "Spec Bot → UX → Builder",
      jeffMode: "caveman",
      lastUpdated: daysAgo(7),
      ops: PROJECT_OPS["proj-points-miles"],
    },
    {
      id: "proj-general-dev",
      name: "General Dev / Utility",
      slug: "general-dev",
      type: "Utilities",
      stack: ["Vite", "React", "Scripts"],
      status: "active",
      priority: "P3",
      path: "C:\\Projects\\language app",
      description: "Side utilities — language translator PWA, scripts, experiments.",
      goals: ["Keep lightweight", "PWA polish"],
      risks: ["Low priority neglect"],
      roadmap: ["Speech UX", "Offline cache"],
      assignedGodBotId: "bot-god-general",
      workerBotIds: ["bot-builder", "bot-debug"],
      preferredInterface: "cursor",
      preferredModelClass: "cheap-fast",
      activeBotStrategy: "Fix worker only",
      jeffMode: "caveman",
      lastUpdated: daysAgo(10),
      ops: PROJECT_OPS["proj-general-dev"],
    },
    {
      id: "proj-jeff-os",
      name: "Jeff OS",
      slug: "jeff-os",
      type: "Meta / DevTools",
      stack: ["Next.js 16", "React 19", "TypeScript", "Tailwind 4"],
      status: "active",
      priority: "P0",
      path: "C:\\Projects\\Project Command\\jeff-mission-control",
      description: "Jeff Mission Control — Easy Mode, verify build, gap/fix prompts, Command Center.",
      goals: ["Dogfood self-build", "Honest verify + gaps", "Easy Mode polish"],
      risks: ["Self-verify while dev running", "Stale localStorage ops"],
      roadmap: ["Self in Projects list", "Live gap truth", "Ship when ready"],
      assignedGodBotId: "bot-god-jeff-os",
      workerBotIds: ["bot-builder", "bot-test", "bot-debug", "bot-docs"],
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      activeBotStrategy: "God Bot + Builder + Test — dogfood",
      godBotFile: "projects/jeff-os.md",
      jeffMode: "caveman",
      lastUpdated: daysAgo(0),
      ops: PROJECT_OPS["proj-jeff-os"],
    },
    {
      id: "proj-new-idea",
      name: "New Project Idea",
      slug: "new-project-idea",
      type: "Greenfield",
      stack: ["TBD"],
      status: "idea",
      priority: "P3",
      description: "Parking lot for new product ideas before they become repos.",
      goals: ["Evaluate fit", "Pick stack", "Estimate effort"],
      risks: ["Too many starters"],
      roadmap: ["Control Tower triage", "Spec Bot draft"],
      assignedGodBotId: "bot-control-tower",
      workerBotIds: ["bot-spec", "bot-architect", "bot-cost"],
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      activeBotStrategy: "Control Tower → Spec",
      jeffMode: "caveman",
      lastUpdated: daysAgo(0),
      ops: PROJECT_OPS["proj-new-idea"],
    },
  ],
  bots: [
    {
      id: "bot-control-tower",
      type: "control-tower",
      name: "Control Tower",
      role: "Portfolio orchestrator",
      description: "Routes Jeff to right project, priority, and handoff.",
      group: "control",
      preferredInterface: "cursor",
      preferredModelClass: "planning-heavy",
      promptPreview: "Read CONTROL_TOWER.md + PROJECT_INDEX.md. Route Jeff.",
      projectIds: [],
    },
    {
      id: "bot-god-jeff-os",
      type: "project-god-bot",
      name: "Jeff OS God Bot",
      role: "Repo owner — Mission Control app",
      description: "Knows jeff-mission-control path, self-build rules, Command Center docs.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      promptPreview: "Read projects/jeff-os.md — dogfood Jeff OS",
      projectIds: ["proj-jeff-os"],
    },
    {
      id: "bot-god-demand",
      type: "project-god-bot",
      name: "Demand Generator God Bot",
      role: "Repo owner — legal demand app",
      description: "Knows vercel generator path, AGENTS.md, port 3001.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      promptPreview: "Read projects/demand-generator-pro.md + AGENTS.md",
      projectIds: ["proj-demand-generator"],
    },
    {
      id: "bot-god-compass",
      type: "project-god-bot",
      name: "Home Compass God Bot",
      role: "Repo owner — household app",
      description: "Emergency, vault, Supabase patterns.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "Read projects/home-compass.md",
      projectIds: ["proj-home-compass"],
    },
    {
      id: "bot-god-travel",
      type: "project-god-bot",
      name: "Kepi Travel God Bot",
      role: "Repo owner — travel platform",
      description: "Build before push. kepi-travel-reborn canonical.",
      group: "project",
      preferredInterface: "claude-code",
      preferredModelClass: "autonomous-heavy",
      promptPreview: "Read projects/kepi-travel.md. npm run build before push.",
      projectIds: ["proj-tripflow"],
    },
    {
      id: "bot-god-keps",
      type: "project-god-bot",
      name: "Keps Trading God Bot",
      role: "Greenfield spec owner",
      description: "Planning-first — no code until spec locked.",
      group: "project",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "Define MVP, risks, data model before build.",
      projectIds: ["proj-keps-trading"],
    },
    {
      id: "bot-god-points",
      type: "project-god-bot",
      name: "Points & Miles God Bot",
      role: "Content product owner",
      description: "Curriculum, UX, content pipeline.",
      group: "project",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "Spec → content model → landing MVP.",
      projectIds: ["proj-points-miles"],
    },
    {
      id: "bot-god-general",
      type: "project-god-bot",
      name: "Language Translator God Bot",
      role: "Utility repo owner",
      description: "Small tools — minimal scope.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "cheap-fast",
      promptPreview: "Keep simple. No backend unless asked.",
      projectIds: ["proj-general-dev"],
    },
    {
      id: "bot-god-bankruptcy",
      type: "project-god-bot",
      name: "My Bankruptcy God Bot",
      role: "Repo owner — ChapterAI monorepo",
      description: "Flagship legal. Never build during dev. Read DEPLOY.md.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      promptPreview: "Read projects/my-bankruptcy.md + repo README.",
      projectIds: ["proj-bankruptcy"],
    },
    {
      id: "bot-god-takeoff",
      type: "project-god-bot",
      name: "Takeoff Pro God Bot",
      role: "Repo owner — contractor takeoff",
      description: "Stage 1 PDF takeoff. Supabase + Prisma patterns.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      promptPreview: "Read projects/takeoff-pro.md + docs/SETUP-SUPABASE.md",
      projectIds: ["proj-takeoff-pro", "proj-takeoff-staging"],
    },
    {
      id: "bot-god-dunning",
      type: "project-god-bot",
      name: "DunningGuard God Bot",
      role: "Repo owner — Stripe dunning SaaS",
      description: "Webhooks, RLS, Connect — security first.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "Read projects/dunningguard.md",
      projectIds: ["proj-dunningguard"],
    },
    {
      id: "bot-god-kepi-search",
      type: "project-god-bot",
      name: "Kepi Search God Bot",
      role: "Repo owner — hotel map explorer",
      description: "MapLibre, city seeds, draw tools.",
      group: "project",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "Read projects/kepi-search.md",
      projectIds: ["proj-kepi-search"],
    },
    {
      id: "bot-god-edgar",
      type: "project-god-bot",
      name: "Edgar God Bot",
      role: "Repo owner — All In One Edgar",
      description: ".NET + Docker + NAS deploy.",
      group: "project",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "Read projects/all-in-one-edgar.md + START-HERE-EDGAR.md",
      projectIds: ["proj-edgar"],
    },
    {
      id: "bot-god-story-pals",
      type: "project-god-bot",
      name: "Story Pals God Bot",
      role: "Repo owner — Flutter app",
      description: "Clarify product goal before big builds.",
      group: "project",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "Read projects/story-pals.md",
      projectIds: ["proj-story-pals"],
    },
    {
      id: "bot-spec",
      type: "spec-bot",
      name: "Spec Bot",
      role: "Requirements & acceptance criteria",
      description: "Turns ideas into shippable specs.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "3 acceptance bullets max. Out of scope list.",
      projectIds: ["proj-new-idea", "proj-points-miles", "proj-keps-trading"],
    },
    {
      id: "bot-architect",
      type: "architect-bot",
      name: "Architect Bot",
      role: "System design",
      description: "Modules, data flow, tradeoffs.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "deep-reasoning",
      promptPreview: "Diagram + decisions. No code yet.",
      projectIds: ["proj-keps-trading", "proj-tripflow"],
    },
    {
      id: "bot-builder",
      type: "builder-bot",
      name: "Builder Bot",
      role: "Implementation",
      description: "Ship features with minimal diff.",
      group: "worker",
      preferredInterface: "cursor",
      preferredModelClass: "code-heavy",
      promptPreview: "Feature Worker rules. Reuse existing components.",
      projectIds: ["proj-demand-generator", "proj-home-compass", "proj-tripflow"],
    },
    {
      id: "bot-reviewer",
      type: "reviewer-bot",
      name: "Reviewer Bot",
      role: "Code review",
      description: "Catch regressions before merge.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "review-heavy",
      promptPreview: "Review diff. Rank issues critical/high/medium.",
      projectIds: [],
    },
    {
      id: "bot-test",
      type: "test-bot",
      name: "Test Bot",
      role: "Tests only",
      description: "Adds/updates tests for behavior.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "code-heavy",
      promptPreview: "Test Worker — no prod logic change unless bug found.",
      projectIds: ["proj-tripflow"],
    },
    {
      id: "bot-debug",
      type: "debug-bot",
      name: "Debug Bot",
      role: "Bug fixes",
      description: "Trace, fix, verify.",
      group: "worker",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "Fix Worker — reproduce first, minimal diff.",
      projectIds: ["proj-general-dev", "proj-demand-generator"],
    },
    {
      id: "bot-refactor",
      type: "refactor-bot",
      name: "Refactor Bot",
      role: "Safe cleanup",
      description: "One module at a time, behavior identical.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "code-heavy",
      promptPreview: "Refactor Worker — explicit scope only.",
      projectIds: [],
    },
    {
      id: "bot-audit",
      type: "audit-bot",
      name: "Audit Bot",
      role: "Quality audit",
      description: "Broad pass for smells and debt.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "review-heavy",
      promptPreview: "Read-only recon + ranked findings.",
      projectIds: [],
    },
    {
      id: "bot-prompt",
      type: "prompt-bot",
      name: "Prompt Bot",
      role: "Prompt engineering",
      description: "Crafts agent prompts and packets.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "planning-heavy",
      promptPreview: "Optimize prompt for task + bot + model class.",
      projectIds: [],
    },
    {
      id: "bot-integration",
      type: "integration-bot",
      name: "Integration Bot",
      role: "API & webhooks",
      description: "Stripe, Supabase, external APIs.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "code-heavy",
      promptPreview: "Wire integration. Idempotent webhooks.",
      projectIds: ["proj-demand-generator", "proj-tripflow"],
    },
    {
      id: "bot-data-model",
      type: "data-model-bot",
      name: "Data Model Bot",
      role: "Schema & migrations",
      description: "Prisma, SQL, RLS design.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "deep-reasoning",
      promptPreview: "Schema change with migration plan.",
      projectIds: ["proj-keps-trading", "proj-home-compass"],
    },
    {
      id: "bot-ux",
      type: "ux-bot",
      name: "UX Bot",
      role: "UI/UX passes",
      description: "Layout, mobile, accessibility.",
      group: "worker",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "UX polish — match existing design system.",
      projectIds: ["proj-home-compass", "proj-points-miles"],
    },
    {
      id: "bot-docs",
      type: "docs-bot",
      name: "Docs Bot",
      role: "Documentation",
      description: "README, setup, AGENTS.md.",
      group: "worker",
      preferredInterface: "cursor",
      preferredModelClass: "cheap-fast",
      promptPreview: "Docs Worker — no app code unless typo.",
      projectIds: ["proj-points-miles"],
    },
    {
      id: "bot-deploy",
      type: "deployment-bot",
      name: "Deployment Bot",
      role: "Ship & deploy",
      description: "Vercel, env, migrations checklist.",
      group: "worker",
      preferredInterface: "cursor",
      preferredModelClass: "balanced",
      promptPreview: "Deploy Worker — checklist + rollback note.",
      projectIds: ["proj-demand-generator", "proj-tripflow"],
    },
    {
      id: "bot-cost",
      type: "cost-bot",
      name: "Cost Bot",
      role: "Cost optimization",
      description: "Model usage, Vercel, infra savings.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "cheap-fast",
      promptPreview: "Find cost leaks. Rank savings.",
      projectIds: ["proj-new-idea", "proj-tripflow"],
    },
    {
      id: "bot-security",
      type: "security-risk-bot",
      name: "Security / Risk Bot",
      role: "Security hardening",
      description: "Auth, RLS, secrets, webhooks.",
      group: "worker",
      preferredInterface: "regular-claude",
      preferredModelClass: "review-heavy",
      promptPreview: "Security Worker — OWASP-minded practical fixes.",
      projectIds: ["proj-demand-generator", "proj-home-compass"],
    },
    {
      id: "bot-pdf",
      type: "integration-bot",
      name: "PDF Worker",
      role: "Document pipelines",
      description: "PDF parse, extract, generate.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "code-heavy",
      promptPreview: "PDF Worker — memory-aware on large files.",
      projectIds: ["proj-demand-generator"],
    },
    {
      id: "bot-ai",
      type: "integration-bot",
      name: "AI Worker",
      role: "LLM pipelines",
      description: "Prompts, extraction, cost-aware models.",
      group: "worker",
      preferredInterface: "claude-code",
      preferredModelClass: "balanced",
      promptPreview: "AI Worker — cache, batch, no key logging.",
      projectIds: ["proj-demand-generator"],
    },
  ],
  tasks: [
    {
      id: "task-1",
      projectId: "proj-demand-generator",
      title: "Security hardening pass",
      description: "Review auth, uploads, admin panel per security roadmap.",
      taskType: "security",
      taskSize: "medium",
      status: "ready",
      priority: "P1",
      selectedBotId: "bot-security",
      selectedInterface: "regular-claude",
      selectedModelClass: "review-heavy",
      recommendedRoute: {
        interface: "regular-claude",
        botType: "security-risk-bot",
        botId: "bot-security",
        modelClass: "review-heavy",
        confidence: 0.82,
        reasons: ["Security task → review-heavy", "Regular Claude for strategy"],
        optimizeFor: "quality",
      },
      routingMode: "auto",
      generatedPrompt: "Security Worker scope: auth, RLS, uploads, admin.",
      resultNotes: "",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: "task-2",
      projectId: "proj-tripflow",
      title: "Fix failing map worker build",
      description: "Build fails on Vercel — trace postinstall patches.",
      taskType: "bugfix",
      taskSize: "small",
      status: "running",
      priority: "P0",
      selectedBotId: "bot-debug",
      selectedInterface: "cursor",
      selectedModelClass: "code-heavy",
      recommendedRoute: {
        interface: "cursor",
        botType: "debug-bot",
        botId: "bot-debug",
        modelClass: "code-heavy",
        confidence: 0.91,
        reasons: ["Small bugfix → Cursor", "Fast file-by-file fix"],
        optimizeFor: "speed",
      },
      routingMode: "auto",
      generatedPrompt: "Fix Worker — reproduce build error first.",
      resultNotes: "Checking maplibre worker copy script.",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
    },
    {
      id: "task-3",
      projectId: "proj-new-idea",
      title: "Evaluate Keps Trading MVP",
      description: "Control Tower triage — worth P2 this quarter?",
      taskType: "planning",
      taskSize: "medium",
      status: "planned",
      priority: "P2",
      selectedBotId: "bot-control-tower",
      selectedInterface: "regular-claude",
      selectedModelClass: "planning-heavy",
      recommendedRoute: {
        interface: "regular-claude",
        botType: "control-tower",
        botId: "bot-control-tower",
        modelClass: "planning-heavy",
        confidence: 0.88,
        reasons: ["Planning → Regular Claude", "Portfolio priority question"],
        optimizeFor: "quality",
      },
      routingMode: "auto",
      generatedPrompt: "Control Tower — rank Keps vs Points vs General.",
      resultNotes: "",
      createdAt: daysAgo(0),
      updatedAt: daysAgo(0),
    },
    {
      id: "task-4",
      projectId: "proj-home-compass",
      title: "Emergency quick page mobile polish",
      description: "FAB, dictation hint, lock screen flow on small screens.",
      taskType: "ux",
      taskSize: "small",
      status: "review",
      priority: "P2",
      selectedBotId: "bot-ux",
      selectedInterface: "cursor",
      selectedModelClass: "balanced",
      recommendedRoute: {
        interface: "cursor",
        botType: "ux-bot",
        botId: "bot-ux",
        modelClass: "balanced",
        confidence: 0.85,
        reasons: ["UI tweak → Cursor", "UX bot for layout pass"],
        optimizeFor: "speed",
      },
      routingMode: "manual",
      generatedPrompt: "UX Bot — mobile emergency flow only.",
      resultNotes: "Ready for Jeff visual review.",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
  ],
  routingPresets: [
    {
      id: "preset-planning-claude",
      name: "Planning → Claude",
      taskType: "planning",
      interface: "regular-claude",
      botType: "architect-bot",
      modelClass: "planning-heavy",
    },
    {
      id: "preset-ship-cursor",
      name: "Quick ship → Cursor",
      taskType: "feature",
      interface: "cursor",
      botType: "builder-bot",
      modelClass: "code-heavy",
    },
    {
      id: "preset-refactor-code",
      name: "Big refactor → Claude Code",
      taskType: "refactor",
      interface: "claude-code",
      botType: "refactor-bot",
      modelClass: "autonomous-heavy",
    },
    {
      id: "preset-demand-security",
      name: "Demand Gen security",
      taskType: "security",
      projectId: "proj-demand-generator",
      interface: "regular-claude",
      botType: "security-risk-bot",
      modelClass: "review-heavy",
    },
  ],
  routingHistory: [
    {
      id: "rh-1",
      projectId: "proj-tripflow",
      taskId: "task-2",
      decision: {
        interface: "cursor",
        botType: "debug-bot",
        botId: "bot-debug",
        modelClass: "code-heavy",
        confidence: 0.91,
        reasons: ["Small bugfix", "Cursor speed"],
        optimizeFor: "speed",
      },
      mode: "auto",
      createdAt: daysAgo(1),
      label: "TripFlow build fix",
    },
    {
      id: "rh-2",
      projectId: "proj-demand-generator",
      label: "PDF pipeline feature",
      decision: {
        interface: "claude-code",
        botType: "builder-bot",
        botId: "bot-builder",
        modelClass: "autonomous-heavy",
        confidence: 0.79,
        reasons: ["Multi-file", "Claude Code autonomous"],
        optimizeFor: "autonomy",
      },
      mode: "auto",
      createdAt: daysAgo(5),
    },
  ],
  workspace: {
    activeProjectId: "proj-demand-generator",
    activeTaskId: "task-2",
    recentProjectIds: ["proj-demand-generator", "proj-tripflow", "proj-home-compass", "proj-new-idea"],
    queueTaskIds: ["task-2", "task-1", "task-4"],
    activeRoute: {
      interface: "cursor",
      botType: "debug-bot",
      botId: "bot-debug",
      modelClass: "code-heavy",
      confidence: 0.91,
      reasons: ["Active task: bugfix", "Cursor for speed"],
      optimizeFor: "speed",
    },
    routeMode: "auto",
    pinnedProjectIds: ["proj-demand-generator", "proj-tripflow"],
    openWorkspaceIds: ["proj-demand-generator"],
    minimizedProjectIds: [],
    handoffNote: "Review TripFlow build on phone. Fix on desktop with Claude Code.",
    voice: {
      lastVoiceCommand: null,
      micPermissionState: "unknown",
    },
  },
  activity: [
    { id: "act-1", type: "routing", message: "Auto-routed TripFlow bugfix → Cursor + Debug Bot", projectId: "proj-tripflow", createdAt: daysAgo(1) },
    { id: "act-2", type: "task", message: "Task ready: Security hardening pass", projectId: "proj-demand-generator", createdAt: daysAgo(1) },
    { id: "act-3", type: "prompt", message: "Generated God Bot packet for Home Compass", projectId: "proj-home-compass", createdAt: daysAgo(2) },
    { id: "act-4", type: "project", message: "Updated New Project Idea roadmap", projectId: "proj-new-idea", createdAt: daysAgo(0) },
    { id: "act-5", type: "bot", message: "Launched Control Tower session", createdAt: daysAgo(0) },
  ],
};

export const STORAGE_KEY = "jeff-mission-control-v9";
