import type { ProjectOps } from "@/lib/types";

const h = (score: number, label: string, status: "good" | "warn" | "bad") => ({
  score,
  label,
  status,
});

export const PROJECT_OPS: Record<string, ProjectOps> = {
  "proj-demand-generator": {
    plainSummary:
      "Legal demand app works locally. Matters + PDF flow live. Security + mobile polish before real client use.",
    readinessLevel: "partially-working",
    buildPhase: "Security hardening + field capture",
    percentComplete: 72,
    readinessScore: 68,
    demoReadyScore: 75,
    productionReadyScore: 52,
    working: ["Matters CRUD", "PDF upload", "Letter preview", "Google auth", "Vercel deploy path"],
    blocked: ["Migration order on fresh DB", "Duplicate folder confusion"],
    whatsNext: ["Security roadmap pass", "Field capture mobile UX", "Admin panel audit"],
    security: h(58, "Needs hardening before prod", "warn"),
    stability: h(74, "Stable in daily dev", "good"),
    quality: h(70, "Good core, edge cases remain", "good"),
    riskLevel: "medium",
    technicalDebt: "medium",
    launchConfidence: 55,
    missingPieces: ["Full security audit", "Mobile field capture ship", "Env docs cleanup"],
    hardeningSteps: ["RLS/auth review", "Upload path scan", "Webhook idempotency check"],
    blockers: ["Security pass not done"],
    errors: [
      {
        id: "err-dg-1",
        title: "Fresh DB migration order fails",
        likelyCause: "20260512 runs before matter_documents table exists",
        severity: "medium",
        fixRisk: "safe",
        confidence: 0.88,
        recommendedFix: "Run 20260513 before 20260512 per AGENTS.md",
        aboutToDo: "Reorder migration apply sequence in bootstrap docs",
        whyDoingIt: "Unblocks new dev environments and CI",
        couldGoWrong: "Wrong order could leave schema half-applied — backup first",
        taskType: "bugfix",
      },
      {
        id: "err-dg-2",
        title: "Port confusion (3000 vs 3001)",
        likelyCause: "README outdated",
        severity: "low",
        fixRisk: "safe",
        confidence: 0.95,
        recommendedFix: "Update README to port 3001",
        aboutToDo: "Patch README + God Bot gotcha",
        whyDoingIt: "Saves debug time every session",
        couldGoWrong: "None",
        taskType: "docs",
      },
    ],
    nextAction: {
      title: "Run security hardening pass",
      milestone: "Production-safe auth + uploads",
      unresolvedIssue: "No completed security audit",
      recommendedPrompt:
        "Security Worker: audit auth, uploads, admin panel. Rank findings. Minimal safe fixes first.",
      whyItMatters: "Legal data — can't ship wide without this",
      effort: "medium",
      impact: "high",
      priority: "P1",
      taskType: "security",
      quickAction: "strengthen-security",
    },
    godModeIdeas: [
      {
        id: "gm-dg-1",
        question: "What is the ultimate never-seen-before version?",
        insight: "AI co-pilot that drafts entire demand from intake call transcript + auto-validates against firm playbook.",
        leverage: "high",
      },
      {
        id: "gm-dg-2",
        question: "Highest leverage next move?",
        insight: "One-click 'firm template' packs — every letter matches partner style without prompt engineering.",
        leverage: "high",
      },
      {
        id: "gm-dg-3",
        question: "What would a god-level architect do next?",
        insight: "Separate read-heavy PDF pipeline to edge worker — cut Vercel cost 40%, faster uploads.",
        leverage: "medium",
      },
    ],
    notes: "Canonical path: C:\\vercel generator",
  },
  "proj-home-compass": {
    plainSummary: "Household app skeleton works. Emergency + vault flows started. Needs mobile polish + Supabase hardening.",
    readinessLevel: "building",
    buildPhase: "Mobile emergency UX",
    percentComplete: 45,
    readinessScore: 48,
    demoReadyScore: 40,
    productionReadyScore: 28,
    working: ["Auth shell", "Household provider", "Emergency routes", "PIN crypto"],
    blocked: ["Family cloud sync incomplete"],
    whatsNext: ["Emergency quick page mobile", "Supabase RLS review", "README replace boilerplate"],
    security: h(62, "PII — needs RLS pass", "warn"),
    stability: h(65, "Dev stable", "good"),
    quality: h(55, "Early — tests thin", "warn"),
    riskLevel: "medium",
    technicalDebt: "low",
    launchConfidence: 35,
    missingPieces: ["Mobile FAB polish", "Family invite flow", "Production Supabase"],
    hardeningSteps: ["RLS policies", "PIN flow audit", "Photo upload limits"],
    blockers: ["No production deploy yet"],
    errors: [],
    nextAction: {
      title: "Polish emergency quick page for mobile",
      milestone: "Demo-ready emergency flow",
      unresolvedIssue: "Small-screen UX not tested",
      recommendedPrompt: "UX Bot: emergency quick page mobile only. Match app shell. Minimal diff.",
      whyItMatters: "Core value prop is emergency access on phone",
      effort: "low",
      impact: "high",
      priority: "P2",
      taskType: "ux",
      quickAction: "continue-build",
    },
    godModeIdeas: [
      {
        id: "gm-hc-1",
        question: "How do we make this exceptional?",
        insight: "One-tap 'ICE mode' — largest text, no login, pre-cached offline vault slice.",
        leverage: "high",
      },
      {
        id: "gm-hc-2",
        question: "World-class missing piece?",
        insight: "Guided household completeness wizard — gamified % like Apple Watch rings.",
        leverage: "medium",
      },
    ],
    notes: "",
  },
  "proj-tripflow": {
    plainSummary: "Large travel platform. Rich features. Vercel build failures cost money. Fork consolidation needed.",
    readinessLevel: "partially-working",
    buildPhase: "Build stability + fork cleanup",
    percentComplete: 65,
    readinessScore: 62,
    demoReadyScore: 70,
    productionReadyScore: 48,
    working: ["Trip store", "Map stack", "Ops APIs", "Test suite"],
    blocked: ["Map worker build intermittent", "3 repo folders"],
    whatsNext: ["Fix postinstall build", "Pick canonical fork", "Build before push CI"],
    security: h(70, "Auth via Clerk — review Connect paths", "good"),
    stability: h(52, "Vercel builds fragile", "warn"),
    quality: h(68, "Strong tests when build passes", "good"),
    riskLevel: "high",
    technicalDebt: "high",
    launchConfidence: 45,
    missingPieces: ["Single canonical repo", "CI build gate", "Cost monitoring"],
    hardeningSteps: ["npm run build in CI", "Remove dead forks", "Sentry alert on deploy fail"],
    blockers: ["Build must pass before every push"],
    errors: [
      {
        id: "err-tf-1",
        title: "Vercel build fails on maplibre worker",
        likelyCause: "postinstall patch script or stale cache",
        severity: "high",
        fixRisk: "medium",
        confidence: 0.82,
        recommendedFix: "Run copy-maplibre-worker locally, fix script, rebuild",
        aboutToDo: "Trace postinstall in kepi-travel-reborn",
        whyDoingIt: "Every failed deploy costs credits",
        couldGoWrong: "Map features break if worker path wrong",
        taskType: "bugfix",
      },
    ],
    nextAction: {
      title: "Fix map worker build — verify npm run build clean",
      milestone: "Reliable Vercel deploys",
      unresolvedIssue: "Intermittent build failure",
      recommendedPrompt: "Fix Worker: reproduce build error. Trace postinstall. Minimal fix.",
      whyItMatters: "Blocks all shipping",
      effort: "medium",
      impact: "high",
      priority: "P0",
      taskType: "bugfix",
      quickAction: "fix-errors",
    },
    godModeIdeas: [
      {
        id: "gm-tf-1",
        question: "Ultimate version of this product?",
        insight: "Personal travel OS — every booking, map, and disruption auto-routed into one timeline with proactive rebooking.",
        leverage: "high",
      },
      {
        id: "gm-tf-2",
        question: "God-level architect next move?",
        insight: "Consolidate to one repo + deploy preview per PR — stop fork entropy now.",
        leverage: "high",
      },
    ],
    notes: "Canonical path: C:\\Projects\\Kepi Travel\\kepi-travel",
  },
  "proj-keps-trading": {
    plainSummary: "Idea stage. No code yet. Need MVP spec before any build.",
    readinessLevel: "idea",
    buildPhase: "Spec + risk model",
    percentComplete: 8,
    readinessScore: 12,
    demoReadyScore: 5,
    productionReadyScore: 0,
    working: ["Concept notes"],
    blocked: ["No MVP defined", "Regulatory unclear"],
    whatsNext: ["Write MVP spec", "Paper trading scope", "Pick data feeds"],
    security: h(40, "N/A — design security in spec", "warn"),
    stability: h(30, "N/A", "warn"),
    quality: h(25, "N/A", "warn"),
    riskLevel: "high",
    technicalDebt: "low",
    launchConfidence: 8,
    missingPieces: ["Everything except idea"],
    hardeningSteps: ["Define compliance boundaries in spec"],
    blockers: ["No spec locked"],
    errors: [],
    nextAction: {
      title: "Lock MVP spec with Architect Bot",
      milestone: "Buildable spec doc",
      unresolvedIssue: "Scope undefined",
      recommendedPrompt: "Architect Bot: Keps Trading MVP — paper trading only, risk limits, data sources. No code.",
      whyItMatters: "Can't build without boundary",
      effort: "medium",
      impact: "high",
      priority: "P2",
      taskType: "planning",
      quickAction: "next-step",
    },
    godModeIdeas: [
      {
        id: "gm-kt-1",
        question: "Highest leverage move?",
        insight: "Start with alert-only paper trading — zero execution risk, proves value fast.",
        leverage: "high",
      },
    ],
    notes: "",
  },
  "proj-points-miles": {
    plainSummary: "Education platform concept. Curriculum outline needed before landing MVP.",
    readinessLevel: "scaffolded",
    buildPhase: "Content model + landing",
    percentComplete: 15,
    readinessScore: 22,
    demoReadyScore: 18,
    productionReadyScore: 10,
    working: ["Name + direction"],
    blocked: ["No content model"],
    whatsNext: ["Curriculum outline", "Landing page MVP", "First lesson template"],
    security: h(75, "Low risk at content stage", "good"),
    stability: h(50, "Not built yet", "warn"),
    quality: h(40, "Early", "warn"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 15,
    missingPieces: ["Content pipeline", "Landing page", "Auth if needed"],
    hardeningSteps: ["Keep static until content pipeline exists"],
    blockers: ["No curriculum"],
    errors: [],
    nextAction: {
      title: "Draft curriculum outline (Spec Bot)",
      milestone: "10-lesson skeleton",
      unresolvedIssue: "No structured content",
      recommendedPrompt: "Spec Bot: Points & Miles curriculum — 10 modules, beginner path. Out of scope: payments.",
      whyItMatters: "Content drives entire product",
      effort: "low",
      impact: "high",
      priority: "P3",
      taskType: "planning",
      quickAction: "next-step",
    },
    godModeIdeas: [
      {
        id: "gm-pm-1",
        question: "Exceptional version?",
        insight: "Interactive 'trip simulator' — user picks city, app shows optimal points strategy live on map.",
        leverage: "high",
      },
    ],
    notes: "",
  },
  "proj-general-dev": {
    plainSummary: "Language translator PWA works. Side utility. Keep lightweight.",
    readinessLevel: "usable",
    buildPhase: "Maintenance",
    percentComplete: 85,
    readinessScore: 80,
    demoReadyScore: 90,
    productionReadyScore: 70,
    working: ["Translation", "Speech", "PWA cache", "Offline-ish"],
    blocked: [],
    whatsNext: ["Speech UX polish", "Optional icon refresh"],
    security: h(80, "Client-only, low attack surface", "good"),
    stability: h(85, "Stable utility", "good"),
    quality: h(75, "Good for scope", "good"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 75,
    missingPieces: ["App store optional"],
    hardeningSteps: ["Rate-limit aware caching"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Small speech UX fix if needed",
      milestone: "Polish pass",
      unresolvedIssue: "None critical",
      recommendedPrompt: "Fix Worker: speech UX only if Jeff reports issue. Keep simple.",
      whyItMatters: "Low priority maintenance",
      effort: "low",
      impact: "low",
      priority: "P3",
      taskType: "bugfix",
      quickAction: "continue-coding",
    },
    godModeIdeas: [
      {
        id: "gm-gd-1",
        question: "World-class twist?",
        insight: "Conversation mode — auto-detect language pair from context, zero picker taps.",
        leverage: "medium",
      },
    ],
    notes: "",
  },
  "proj-bankruptcy": {
    plainSummary: "Flagship bankruptcy platform. Mature monorepo. Production-minded — dev/build split critical.",
    readinessLevel: "production-ready",
    buildPhase: "Feature ship + e-file stability",
    percentComplete: 78,
    readinessScore: 82,
    demoReadyScore: 85,
    productionReadyScore: 72,
    working: ["Matters", "Command center", "API + worker", "E-file bridge"],
    blocked: ["Duplicate Bankrupty folder"],
    whatsNext: ["E-file hardening", "Worker reliability", "Deploy checklist"],
    security: h(75, "Legal data — ongoing hardening", "good"),
    stability: h(78, "Mature but complex", "good"),
    quality: h(80, "Strong test culture", "good"),
    riskLevel: "medium",
    technicalDebt: "medium",
    launchConfidence: 70,
    missingPieces: ["Production deploy runbook refresh"],
    hardeningSteps: ["Auth audit", "E-file error paths", "Worker retry policy"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Continue flagship feature work",
      milestone: "Next v0.6 milestone",
      unresolvedIssue: "Pick top P0 from roadmap",
      recommendedPrompt: "God Bot: read my-bankruptcy.md. Continue top P0 feature. Minimal diff. No build during dev.",
      whyItMatters: "P0 revenue product",
      effort: "medium",
      impact: "high",
      priority: "P0",
      taskType: "feature",
      quickAction: "continue-build",
    },
    godModeIdeas: [
      {
        id: "gm-bk-1",
        question: "Ultimate version?",
        insight: "Full practice OS — intake to discharge with AI co-pilot at every step.",
        leverage: "high",
      },
      {
        id: "gm-bk-2",
        question: "Beat every intake product?",
        insight: "Mobile-first client intake with doc scan, OCR, and auto-populated schedules — zero re-typing for staff.",
        leverage: "high",
      },
      {
        id: "gm-bk-3",
        question: "Means test that never lies?",
        insight: "Eligibility engine that flags CMI issues before filing — with plain-English explainers for clients.",
        leverage: "high",
      },
      {
        id: "gm-bk-4",
        question: "Creditor matrix on autopilot?",
        insight: "Import claims, dedupe creditors, and generate matrix + mailing labels from one upload.",
        leverage: "medium",
      },
      {
        id: "gm-bk-5",
        question: "E-file errors competitors fear?",
        insight: "Retry queue + human-readable fix paths when CM/ECF rejects — staff never stares at raw XML.",
        leverage: "high",
      },
      {
        id: "gm-bk-6",
        question: "Practice pulse for partners?",
        insight: "Partner dashboard: filings in pipeline, bottlenecks, and revenue-at-risk before Monday meeting.",
        leverage: "long-term",
      },
    ],
    notes: "Canonical: C:\\Projects\\ChapterAI",
  },
  "proj-takeoff-pro": {
    plainSummary: "Stage 1 takeoff shipped. PDF viewer + org model works. Stages 2–5 on roadmap.",
    readinessLevel: "partially-working",
    buildPhase: "Stage 1 polish → Stage 2",
    percentComplete: 55,
    readinessScore: 58,
    demoReadyScore: 65,
    productionReadyScore: 42,
    working: ["PDF upload", "Sheet model", "Viewer", "Org/project CRUD"],
    blocked: ["Supabase local setup friction"],
    whatsNext: ["Stage 2 takeoff tools", "Supabase docs verify", "Export MVP"],
    security: h(68, "Auth via Supabase — review RLS", "good"),
    stability: h(70, "Stable Stage 1", "good"),
    quality: h(65, "Good foundation", "good"),
    riskLevel: "medium",
    technicalDebt: "low",
    launchConfidence: 50,
    missingPieces: ["Stage 2 features", "Billing"],
    hardeningSteps: ["RLS audit", "Upload size limits"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Polish Stage 1 or start Stage 2 spike",
      milestone: "Demo-ready takeoff flow",
      unresolvedIssue: "Jeff picks Stage 1 vs 2 focus",
      recommendedPrompt: "God Bot: takeoff-pro.md. Stage 1 polish OR Stage 2 spike — Jeff picks one.",
      whyItMatters: "P0 product build",
      effort: "medium",
      impact: "high",
      priority: "P0",
      taskType: "feature",
      quickAction: "continue-build",
    },
    godModeIdeas: [],
    notes: "",
  },
  "proj-dunningguard": {
    plainSummary: "Mature Stripe dunning micro-SaaS. Shippable shape. Webhook + RLS need ongoing care.",
    readinessLevel: "beta",
    buildPhase: "Ship + harden webhooks",
    percentComplete: 75,
    readinessScore: 78,
    demoReadyScore: 82,
    productionReadyScore: 68,
    working: ["Stripe Connect", "Dunning emails", "Dashboard", "Vercel deploy"],
    blocked: [],
    whatsNext: ["Webhook idempotency audit", "Onboarding polish", "Analytics"],
    security: h(72, "Payments — webhook focus", "good"),
    stability: h(80, "Mature SaaS shape", "good"),
    quality: h(75, "Solid", "good"),
    riskLevel: "medium",
    technicalDebt: "low",
    launchConfidence: 72,
    missingPieces: ["Marketing site polish"],
    hardeningSteps: ["Webhook replay test", "RLS review"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Webhook + RLS security pass",
      milestone: "Production-safe payments",
      unresolvedIssue: "Routine hardening not scheduled",
      recommendedPrompt: "Security Worker: DunningGuard webhooks + Supabase RLS. Rank findings. Safe fixes first.",
      whyItMatters: "Money + customer data",
      effort: "medium",
      impact: "high",
      priority: "P1",
      taskType: "security",
      quickAction: "strengthen-security",
    },
    godModeIdeas: [],
    notes: "",
  },
  "proj-kepi-search": {
    plainSummary: "Hotel map explorer works. Draw + search flow live. City seeds need maintenance.",
    readinessLevel: "partially-working",
    buildPhase: "Map UX + more cities",
    percentComplete: 60,
    readinessScore: 62,
    demoReadyScore: 70,
    productionReadyScore: 45,
    working: ["Map draw", "Hotel search", "City seeds"],
    blocked: [],
    whatsNext: ["More city seeds", "Mobile layout", "Save searches"],
    security: h(78, "Personal tool — low risk", "good"),
    stability: h(72, "Stable for personal use", "good"),
    quality: h(68, "Good map UX", "good"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 55,
    missingPieces: ["Persistence layer optional"],
    hardeningSteps: ["API key rotation docs"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Add next city seed or mobile polish",
      milestone: "Personal daily-driver map",
      unresolvedIssue: "Jeff picks city vs UX",
      recommendedPrompt: "Feature Worker: Kepi Search — one city seed OR mobile map polish. Minimal diff.",
      whyItMatters: "Personal tool Jeff actually uses",
      effort: "low",
      impact: "medium",
      priority: "P2",
      taskType: "feature",
      quickAction: "continue-build",
    },
    godModeIdeas: [],
    notes: "",
  },
  "proj-edgar": {
    plainSummary: ".NET + Docker office ops platform. NAS deploy path. Agents + sign-in web app.",
    readinessLevel: "partially-working",
    buildPhase: "NAS deploy stability",
    percentComplete: 55,
    readinessScore: 58,
    demoReadyScore: 60,
    productionReadyScore: 48,
    working: ["Sign-in app", "Docker compose", "Agent concept"],
    blocked: ["NAS-specific config"],
    whatsNext: ["Agent health monitoring", "Deploy docs", "Auth hardening"],
    security: h(70, "Entra auth — review agent trust", "good"),
    stability: h(62, "Infra-dependent", "warn"),
    quality: h(65, "Solid .NET base", "good"),
    riskLevel: "medium",
    technicalDebt: "medium",
    launchConfidence: 50,
    missingPieces: ["Agent auto-update", "Monitoring"],
    hardeningSteps: ["Entra config audit", "Docker secrets"],
    blockers: [],
    errors: [],
    nextAction: {
      title: "NAS deploy health check",
      milestone: "Reliable office deploy",
      unresolvedIssue: "Agent update path unclear",
      recommendedPrompt: "Deploy Worker: Edgar NAS Docker — verify deploy path, document agent update flow.",
      whyItMatters: "Infra product Jeff relies on",
      effort: "medium",
      impact: "high",
      priority: "P2",
      taskType: "deploy",
      quickAction: "continue-build",
    },
    godModeIdeas: [],
    notes: "Start with START-HERE-EDGAR.md",
  },
  "proj-story-pals": {
    plainSummary: "Flutter scaffold. Product goal still fuzzy. Needs spec before big build.",
    readinessLevel: "scaffolded",
    buildPhase: "Product spec",
    percentComplete: 12,
    readinessScore: 18,
    demoReadyScore: 10,
    productionReadyScore: 5,
    working: ["Flutter shell", "GitHub repo"],
    blocked: ["Product goal unclear"],
    whatsNext: ["Spec session", "Core loop wireframe", "First screen"],
    security: h(80, "Early — low risk", "good"),
    stability: h(50, "Scaffold only", "warn"),
    quality: h(40, "Template README", "warn"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 12,
    missingPieces: ["Product definition", "Core gameplay/loop"],
    hardeningSteps: [],
    blockers: ["Needs product spec"],
    errors: [],
    nextAction: {
      title: "Spec Bot: define Story Pals core loop",
      milestone: "Buildable 1-pager",
      unresolvedIssue: "What is the app?",
      recommendedPrompt: "Spec Bot: Story Pals — 3-sentence product, core loop, out of scope. No code.",
      whyItMatters: "Can't build without direction",
      effort: "low",
      impact: "high",
      priority: "P3",
      taskType: "planning",
      quickAction: "next-step",
    },
    godModeIdeas: [],
    notes: "",
  },
  "proj-takeoff-staging": {
    plainSummary: "Empty Next staging shell. Use Takeoff Pro for real work unless spiking.",
    readinessLevel: "scaffolded",
    buildPhase: "Spike only",
    percentComplete: 10,
    readinessScore: 15,
    demoReadyScore: 5,
    productionReadyScore: 0,
    working: ["Next scaffold"],
    blocked: ["Not main codebase"],
    whatsNext: ["Archive or use for spike"],
    security: h(70, "Empty shell", "good"),
    stability: h(60, "N/A", "good"),
    quality: h(30, "Bare scaffold", "warn"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 5,
    missingPieces: ["Purpose decision"],
    hardeningSteps: [],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Skip unless Jeff assigns spike",
      milestone: "N/A",
      unresolvedIssue: "Duplicate of Takeoff Pro",
      recommendedPrompt: "Control Tower: skip staging unless Jeff says spike task.",
      whyItMatters: "Avoid wasted effort",
      effort: "low",
      impact: "low",
      priority: "P3",
      taskType: "exploration",
      quickAction: "what-to-do",
    },
    godModeIdeas: [],
    notes: "",
  },
  "proj-new-idea": {
    plainSummary: "Parking lot for greenfield ideas. Control Tower triage only.",
    readinessLevel: "idea",
    buildPhase: "Triage",
    percentComplete: 5,
    readinessScore: 10,
    demoReadyScore: 0,
    productionReadyScore: 0,
    working: ["Capture slot exists"],
    blocked: ["No idea selected"],
    whatsNext: ["Pick idea", "Spec Bot draft", "Cost Bot estimate"],
    security: h(50, "N/A", "warn"),
    stability: h(50, "N/A", "warn"),
    quality: h(50, "N/A", "warn"),
    riskLevel: "low",
    technicalDebt: "low",
    launchConfidence: 5,
    missingPieces: ["Chosen concept"],
    hardeningSteps: [],
    blockers: ["Needs Jeff pick"],
    errors: [],
    nextAction: {
      title: "Control Tower: rank greenfield options",
      milestone: "Pick one idea to promote",
      unresolvedIssue: "Too many starters",
      recommendedPrompt: "Control Tower: compare Keps vs Points vs new idea. Pick one for Q3.",
      whyItMatters: "Focus beats sprawl",
      effort: "low",
      impact: "medium",
      priority: "P3",
      taskType: "planning",
      quickAction: "what-to-do",
    },
    godModeIdeas: [
      {
        id: "gm-ni-1",
        question: "What are we missing for world-class portfolio?",
        insight: "One 'spike week' ritual — kill or promote every idea folder monthly.",
        leverage: "long-term",
      },
    ],
    notes: "",
  },
  "proj-jeff-os": {
    plainSummary: "Jeff OS — Easy Mode dashboard. Dogfood: build and verify this app while using it.",
    readinessLevel: "partially-working",
    buildPhase: "Self-build + honest gaps",
    percentComplete: 72,
    readinessScore: 70,
    demoReadyScore: 75,
    productionReadyScore: 55,
    working: [
      "Easy Mode UI",
      "Folder scan + brief",
      "Verify build (npm run build)",
      "Error fix + gap fix prompts",
      "Docs tab",
    ],
    blocked: [],
    whatsNext: [],
    security: h(75, "Local-first — no cloud secrets in repo", "good"),
    stability: h(72, "Verify while dev running — rare .next race", "good"),
    quality: h(78, "Typecheck + build + CI on push", "good"),
    riskLevel: "low",
    technicalDebt: "medium",
    launchConfidence: 70,
    missingPieces: [],
    hardeningSteps: [],
    blockers: [],
    errors: [],
    nextAction: {
      title: "Pick next Jeff OS feature — verify with Rescan + build",
      milestone: "Dogfood loop works",
      unresolvedIssue: "Self not in project list (fixed in catalog)",
      recommendedPrompt: "Read projects/jeff-os.md. Build [feature]. npm run build clean.",
      whyItMatters: "Jeff OS must manage itself like any product",
      effort: "medium",
      impact: "high",
      priority: "P0",
      taskType: "feature",
      quickAction: "continue-build",
    },
    godModeIdeas: [
      {
        id: "gm-jo-1",
        question: "What makes Jeff OS world-class?",
        insight: "One screen: truth on disk, one button: copy Cursor prompt, zero stale seed lies.",
        leverage: "high",
      },
    ],
    notes: "App: jeff-mission-control. Docs: docs/command-center inside repo.",
  },
};

export function defaultOps(projectId: string, name: string): ProjectOps {
  return (
    PROJECT_OPS[projectId] ?? {
      plainSummary: `${name} — ops data pending scan.`,
      readinessLevel: "building",
      buildPhase: "Unknown",
      percentComplete: 50,
      readinessScore: 50,
      demoReadyScore: 40,
      productionReadyScore: 30,
      working: [],
      blocked: [],
      whatsNext: ["Run Scan Worker"],
      security: h(50, "Unknown", "warn"),
      stability: h(50, "Unknown", "warn"),
      quality: h(50, "Unknown", "warn"),
      riskLevel: "medium",
      technicalDebt: "medium",
      launchConfidence: 40,
      missingPieces: ["Project scan"],
      hardeningSteps: [],
      blockers: [],
      errors: [],
      nextAction: {
        title: "Scan project repo",
        milestone: "Ops populated",
        unresolvedIssue: "No ops data",
        recommendedPrompt: "Scan Worker: infer readiness from repo",
        whyItMatters: "Jeff OS needs truth",
        effort: "low",
        impact: "medium",
        priority: "P2",
        taskType: "exploration",
        quickAction: "what-to-do",
      },
      godModeIdeas: [],
      notes: "",
    }
  );
}

export function attachOps<T extends { id: string; name: string }>(project: T): T & { ops: ProjectOps } {
  return { ...project, ops: PROJECT_OPS[project.id] ?? defaultOps(project.id, project.name) };
}
